server {
	listen 80;
	server_name YOUR_SERVER_NAME;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name YOUR_SERVER_NAME;

	ssl_certificate PATH_TO_CERT;
	ssl_certificate_key PATH_TO_KEY;

	location / {
		proxy_pass http://127.0.0.1:6895;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
	}
}
		


